In [8]:
a = 'Chuck'
b = 'hello ' + a 

print(b)

hello Chuck


In [10]:
hours = 35
rate = 2.75
pay = hours*rate
print(pay)

96.25


In [26]:
width = 17
height = 12.0

In [16]:
width//2

8

In [17]:
width/2.0

8.5

In [23]:
height/3

4.0

In [27]:
8 + 8.5 \* 5

SyntaxError: unexpected character after line continuation character (<ipython-input-27-667b26743f02>, line 1)

In [28]:
celsius = float(input("Enter temperature in celsius: "))
fahrenheit = (celsius * 9/5) + 32
print('%.2f Celsius is: %0.2f Fahrenheit' %(celsius, fahrenheit))

Enter temperature in celsius:  60


60.00 Celsius is: 140.00 Fahrenheit


In [39]:
celsius = 60
fahrenheit = (celsius *(9/5)) + 32
fahrenheit

140.0

In [41]:
hours = 45
rate= 10.5
pay = hours * rate
print(pay)

472.5


boolean

In [1]:
hours = 45
rate = 10

if hours <= 40:
    print(hours * rate)
elif hours>40:
    print(40* rate + (hours-40)*1.5*rate)

475.0


In [6]:
score = (">= 0.9, >= 0.8, >= 0.7, >= 0.6, < 0.6")
a = (0.7)
if 0.0 < a > 1.0:
    print(" score of out of range")
elif a >= 0.9:
        print("A")
elif a >= 0.8:
            print(B)
elif a >= 0.7:
                print("C")
elif a >= 0.6:
                    print("D")
elif a < 0.6:
                        print("F")

C


In [7]:
score = (">= 0.9, >= 0.8, >= 0.7, >= 0.6, < 0.6")
a = (10.0)
if 0.0 < a > 1.0:
    print(" score of out of range")
elif a >= 0.9:
        print("A")
elif a >= 0.8:
            print(B)
elif a >= 0.7:
                print("C")
elif a >= 0.6:
                    print("D")
elif a < 0.6:
                        print("F")

 score of out of range


In [ ]:
num = 0
tot = 0.0
while True:
    number = input("Enter a number")
    if number == 'done':
        break
    try :
        num1 = float(number)
    except:
        print('Invailed Input')
        continue
    num = num+1
    tot = tot + num1
print ('all done')
print (tot,num,tot/num)

In [1]:
score = (">= 0.9, >= 0.8, >= 0.7, >= 0.6, < 0.6")
a = (10.0)
if 0.0 < a > 1.0:
    print(" error")
elif a >= 0.9:
        print("A")
elif a >= 0.8:
            print(B)
elif a >= 0.7:
                print("C")
elif a >= 0.6:
                    print("D")
elif a < 0.6:
                        print("F")

 error


In [7]:
num = 6
tot = 6.7
while true: 
    numer = (6)
    if number == 'done':
        break
    try : 
        num1 = (7)
    except :
            print('wrong')
            continue
            num =num+1
            tot =tot + num1
            print ('all done')
print (tot,num,tot/num)

NameError: name 'true' is not defined

In [11]:
# [:] means that all latters in fruit should be printed since no value was assing to it 
s = "fruit"
print(s[:])

fruit


In [33]:
 count = 5
a = 'apple' 
count == a
print(count)

5


In [61]:
def countLetters(str, ch):
    fruit = str
count = 0
for char in fruit:
    if char == ch:
count = count + 1
print count

IndentationError: expected an indented block (<ipython-input-61-a7ef88cb5040>, line 6)

In [64]:
def countLetters(str, ch):
    fruit = str
count = 0
for char in fruit:
    if char == ch:
count = count + 1
    print count

IndentationError: expected an indented block (<ipython-input-64-6e273bd251eb>, line 6)

NUMPY

In [144]:
# all() returns true if all item in a giving element is true, other wise returns false
# all() returns true if the iterable object is empty

b1 = (1,2,4,6)
print(all(b1))

True


In [145]:
b2 = (0,0.9,0,8)
print(all(b2))

False


In [146]:
b3 = ()
print(all(b3))

True


In [124]:
# any()returns True if at least one item in an iterable is True.
# any() method calculates whether any value in an iterable object a list, string, or tuple is equal to True and returns True,otherwise,
# any() returns False.

p1 = (4, 3, 8, 7)
print(any(p1))

True


In [125]:
p2= (0,1,2,3)
print(any(p2))

True


In [41]:
p4 = (0,0,False)
print(any(p4))

False


In [43]:
# all() checks for all the elements if bool(element) is true or not. 

f1 = (6, 4, 8, 9)
print(all(f1))

True


In [45]:
f2= (0,7,5,3)
print(all(f2))

False


In [46]:
f4 = (True,0,False)
print(all(f4))

False


In [120]:
# cumprod() is used to find the cumulative product of the values seen so far over any axis.

import numpy as np
r = np.array([2, 5, 8])
np.cumprod(r)

array([ 2, 10, 80], dtype=int32)

In [127]:
f = np.array([[2,5,4],[5,4,9]])
np.cumprod(f)

array([   2,   10,   40,  200,  800, 7200], dtype=int32)

In [130]:
# cumsum is used to find the cumulative sum of array in a giving element of an axies
 
n = np.array([[2,5,4],[5,4,9]])
np.cumsum(n)

array([ 2,  7, 11, 16, 20, 29], dtype=int32)

In [138]:
# reshape() is used to give a new shape to an array without changing its data.
import numpy as np

a = np.array([[1,4,5,7],[8,5,6,7],[11,5,9,3],[10,3,5,9]])
a

array([[ 1,  4,  5,  7],
       [ 8,  5,  6,  7],
       [11,  5,  9,  3],
       [10,  3,  5,  9]])

In [142]:
import math
t = np.array(math.pi/3)
np.cos(t)
f = np.array(math.pi/3)
np.cosh(f)

1.600286857702386

EXERCISES

In [3]:
n = 4
if n % 2 == 1:
    print('weird')
elif n % 2== 0 and n in range (2,5):
    print('not weired')
# elif n%2 == 0:
#      for n in range(6,20:)
#     print('weird')
# else:
#     if (n%2==0 & n.20):
#       print("not werid")




not weired


In [101]:
i = ()
n = 7
for i in range(0,5):
    print(i**2)
    

0
1
4
9
16


string split and join

In [102]:
a = "this is a string"
a = "-".join(a)
print(a)

t-h-i-s- -i-s- -a- -s-t-r-i-n-g


In [1]:
b = "i am a girl"
b = b.split(" ") 
print(b)

['i', 'am', 'a', 'girl']


In [2]:
b = "-".join(b)
print(b)

i-am-a-girl


In [109]:
a = "hello world"
b = a.title()
print(b)

Hello World


In [148]:
b = "chris alin"
x = b.title() 
print(x)

Chris Alin


NESTED

In [ ]:
students = [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41], ['Harsh', 39]
            